# Generated by Django 4.2.1 on 2023-05-28 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('propriedade_local', models.CharField(max_length=100, verbose_name='Propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsaveisTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('numero_registro', models.CharField(max_length=20, verbose_name='Número CREA/CFTA')),
                ('produtores_rurais', models.ManyToManyField(to='cadastros.produtorrural', verbose_name='Produtor Rural')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('produtor_rural', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produtorrural', verbose_name='Produtor Rural')),
            ],
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='responsaveis_tecnicos',
            field=models.ManyToManyField(to='cadastros.responsaveistecnicos', verbose_name='Responsáveis Técnicos'),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100, verbose_name='Cultura')),
                ('produto_comercial', models.CharField(max_length=100, verbose_name='Produto Comercial')),
                ('alvo', models.CharField(max_length=100, verbose_name='Alvo')),
                ('area_a_tratar', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Área a tratar')),
                ('volume_da_calda', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Volume de calda')),
                ('intervalo_de_seguranca', models.IntegerField(verbose_name='Intervalo de segurança')),
                ('modalidade_aplicacao', models.CharField(max_length=100, verbose_name='Modalidade de aplicação')),
                ('equipamento_aplicacao', models.CharField(max_length=100, verbose_name='Equipamento de aplicação')),
                ('quantidade_a_adquirir', models.IntegerField(verbose_name='Quantidade a adquirir')),
                ('n_aplicacoes', models.IntegerField(verbose_name='Nº aplicação')),
                ('epoca_aplicacao', models.CharField(max_length=100, verbose_name='Época de aplicação')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.propriedade')),
            ],
        ),
    ]
