# Generated by Django 4.2.1 on 2023-05-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtorrural',
            name='responsaveis_tecnicos',
        ),
    ]
