# Generated by Django 4.2.1 on 2023-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_produtorrural_responsaveis_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtorrural',
            name='responsaveis_tecnicos',
            field=models.ManyToManyField(to='cadastros.responsaveistecnicos', verbose_name='Responsáveis Técnicos'),
        ),
    ]
