# Generated by Django 4.2.1 on 2023-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_responsaveistecnicos_produtores_rurais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsaveistecnicos',
            name='produtores_rurais',
            field=models.ManyToManyField(blank=True, to='cadastros.produtorrural', verbose_name='Produtor Rural'),
        ),
    ]
