# Generated by Django 4.2.1 on 2023-05-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_responsaveistecnicos_produtores_rurais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtorrural',
            old_name='nome',
            new_name='nome_rural',
        ),
        migrations.RenameField(
            model_name='propriedade',
            old_name='cnpj',
            new_name='cnpj_propriedade',
        ),
        migrations.RenameField(
            model_name='responsaveistecnicos',
            old_name='cnpj',
            new_name='cnpj_tecnico',
        ),
        migrations.RenameField(
            model_name='responsaveistecnicos',
            old_name='nome',
            new_name='nome_tecnico',
        ),
    ]
